Repository NUTFes/chosei-chan, pull requests merged in 2023-07, with the labels that each got.

#5 inputコンポーネントの作成
  .gitignore
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Input/Input.types.ts
  src/components/common/Input/index.ts
  src/components/common/index.ts
  tailwind.config.js
Labels: enhancement

#14 [fix] Buttonコンポーネントの修正
  postcss.config.cjs
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/Button.types.ts
  src/pages/index.tsx
Labels: bug

#7 [feat]Headerコンポーネントの作成とthemeの設定
  src/components/common/Header/Header.stories.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/index.ts
  src/components/common/index.ts
  tailwind.config.js
Labels: enhancement

#13 [feat]collapseコンポーネントの作成
  src/components/common/Collapse/Collapse.stories.tsx
  src/components/common/Collapse/Collapse.tsx
  src/components/common/Collapse/Collapse.types.ts
  src/components/common/Collapse/index.ts
Labels: enhancement

#8 [feat] textareaコンポーネントの作成
  src/components/common/TextArea/TextArea.stories.tsx
  src/components/common/TextArea/TextArea.tsx
  src/components/common/TextArea/TextArea.types.ts
  src/components/common/TextArea/index.ts
Labels: enhancement

#19 [feat] eslint, prettierの設定を追加
  .eslintrc.json
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  postcss.config.cjs
  src/pages/index.tsx
  tsconfig.json
Labels: enhancement

#20 [fix] フッターのリンクアイコン、文字にホバー処理を追加&MainLayoutの作成、ヘッダーのカラー変更
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/Header.tsx
  src/components/layout/MainLayout/MainLayout.tsx
  src/components/layout/MainLayout/index.ts
  src/pages/index.tsx
Labels: enhancement

#24 [feat]memoListの作成
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
  src/components/screen/MemoList/MemoList.stories.tsx
  src/components/screen/MemoList/MemoList.tsx
  src/components/screen/MemoList/MemoList.types.ts
  src/components/screen/MemoList/index.ts
  src/constant/users.ts
  src/type/common.ts
Labels: enhancement

#26 [Feat]開発用データの追加
  .github/release.yml
  .github/workflows/auto-build.yml
  .github/workflows/auto-prettier.yml
  src/components/screen/MemoList/MemoList.stories.tsx
  src/constant/data.ts
  src/constant/users.ts
  src/type/common.ts
Labels: enhancement

#22 [feat]calenderコンポーネントの作成
  package-lock.json
  package.json
  src/components/screen/Calender/Calender.stories.tsx
  src/components/screen/Calender/Calender.tsx
  src/components/screen/Calender/Calender.types.ts
  src/components/screen/Calender/index.ts
  src/components/screen/index.ts
Labels: enhancement

#28 [feat]メインページの外観作成
  src/components/common/Footer/Footer.tsx
  src/components/common/Input/Input.tsx
  src/components/common/TextArea/TextArea.tsx
  src/pages/index.tsx
Labels: enhancement

#31 [feat]メモリストをchat形式にする
  src/components/screen/MemoList/MemoList.tsx
Labels: enhancement

#32 [feat]shareButtonコンポーネントの作成
  package-lock.json
  package.json
  public/LINE_Brand_icon.png
  src/components/common/ShareButton/ShareButton.stories.tsx
  src/components/common/ShareButton/ShareButton.tsx
  src/components/common/ShareButton/ShareButton.type.ts
  src/components/common/ShareButton/index.ts
Labels: enhancement

#35 Update auto-prettier.yml
  .github/workflows/auto-prettier.yml
Labels: bug

#37 [fix] prettierによる修正
  package.json
  src/components/common/Button/Button.types.ts
  src/components/common/Button/index.ts
  src/components/common/Collapse/Collapse.stories.tsx
  src/components/common/Collapse/Collapse.tsx
  src/components/common/Collapse/Collapse.types.ts
  src/components/common/Collapse/index.ts
  src/components/common/Footer/Footer.stories.tsx
  src/components/common/Footer/index.tsx
  src/components/common/Header/Header.stories.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/index.ts
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/Input.types.ts
  src/components/common/Input/index.ts
  src/components/common/ShareButton/index.ts
  src/components/common/TextArea/TextArea.stories.tsx
  src/components/common/TextArea/TextArea.types.ts
  src/components/common/TextArea/index.ts
  src/components/common/index.ts
  src/components/layout/MainLayout/MainLayout.tsx
  src/components/layout/MainLayout/index.ts
  src/components/screen/Calender/index.ts
  src/components/screen/index.ts
  src/pages/_document.tsx
  src/pages/api/hello.ts
Labels: bug

#42 日付をドラッグでまとめて指定できるように
  package-lock.json
  src/components/screen/Calender/Calender.tsx
Labels: enhancement

#33 [feat] 日程調整ページの作成
  src/components/common/Footer/Footer.tsx
  src/components/layout/MainLayout/MainLayout.tsx
  src/pages/[scheduleId]/index.tsx
Labels: enhancement

#49 memolistのレスポンシブ対応
  .storybook/main.ts
  .storybook/preview.ts
  src/components/screen/MemoList/MemoList.tsx
  src/styles/globals.css
Labels: bug, enhancement

#40 [feat]firebaseのデータに関するメソッドの作成
  package-lock.json
  package.json
  src/constant/data.ts
  src/pages/test.tsx
  src/repositories/index.js
  src/repositories/schedule.ts
  src/repositories/user.ts
  src/type/common.ts
Labels: enhancement

#48 日程入力コンポーネントの実装
  src/components/screen/ScheduleInput/ScheduleInput.stories.tsx
  src/components/screen/ScheduleInput/ScheduleInput.tsx
  src/components/screen/ScheduleInput/ScheduleInput.types.ts
  src/components/screen/ScheduleInput/index.ts
  src/components/screen/index.ts
  src/utils/dayDivideHalfHour.ts
Labels: enhancement

#55 [feat]入力ページのフォームデータをfirebaseに追加
  src/pages/index.tsx
  src/repositories/schedule.ts
Labels: enhancement

#56 [fix] フッターのレスポンシブ対応
  src/components/common/Footer/Footer.tsx
Labels: bug, enhancement

#52 [feat]日程調整ページの作成
  src/components/common/index.ts
  src/components/screen/MemoList/MemoList.tsx
  src/components/screen/MemoList/MemoList.types.ts
  src/components/screen/ScheduleDisplay/ScheduleDisplay.tsx
  src/pages/[scheduleId]/index.tsx
Labels: enhancement

#58 [feat]日程入力ページの作成
  src/pages/[scheduleId]/create.tsx
Labels: enhancement

#62 [feat]ユーザーの入力データをfirebaseに追加
  src/pages/[scheduleId]/create.tsx
Labels: enhancement

#59 [fix]ボタンの位置のレスポンシブ対応
  src/pages/[scheduleId]/index.tsx
Labels: enhancement

#64 [feat] 予定調整ページでユーザの名前表示
  src/components/screen/MemoList/MemoList.tsx
  src/pages/[scheduleId]/index.tsx
  src/pages/index.tsx
Labels: enhancement

#69 [Fix]scheduleDisplayの色変更
  src/components/screen/ScheduleDisplay/ScheduleDisplay.tsx
Labels: enhancement

#70 [feat]calenderDisplayホバー時に名前を表示
  src/components/screen/ScheduleDisplay/ScheduleDisplay.tsx
  src/styles/globals.css
Labels: enhancement

#67 [fix] ヘッダーのロゴ搭載、追加ボタン強調、参加者バッジ変更
  public/header_logo.svg
  src/components/common/Header/Header.tsx
  src/pages/[scheduleId]/create.tsx
  src/pages/[scheduleId]/index.tsx
  src/pages/index.tsx
Labels: bug, enhancement

#74 [fix] 調整ちゃん全体のデザイン修正
  src/components/common/Button/Button.tsx
  src/components/common/Header/Header.tsx
  src/components/screen/MemoList/MemoList.tsx
  src/components/screen/ScheduleDisplay/ScheduleDisplay.tsx
  src/pages/[scheduleId]/create.tsx
  src/pages/[scheduleId]/index.tsx
  src/pages/index.tsx
  src/styles/globals.css
  src/type/common.ts
Labels: enhancement

#76 [feat]userの更新ページの実装
  src/pages/[scheduleId]/edit.tsx
Labels: enhancement

#78 [fix]testページ削除
  src/pages/test.tsx
Labels: enhancement

#81 [feat]scheduleをCarouselで表示する
  src/components/screen/ScheduleDisplay/ScheduleDisplay.tsx
  src/components/screen/ScheduleInput/ScheduleInput.tsx
  src/pages/[scheduleId]/create.tsx
  src/pages/[scheduleId]/index.tsx
Labels: enhancement

#92 [fix]Line共有ボタンのホバーデザインを追加
  src/components/common/ShareButton/ShareButton.tsx
Labels: bug

#90 [fix]トップページサイズの変更
  src/pages/index.tsx
Labels: bug

#85 [fix]memoListの色変更
  src/components/screen/MemoList/MemoList.tsx
Labels: enhancement
